/** @type {import('jest').Config} */
module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  rootDir: ".",
  roots: ["<rootDir>/src"],
  testMatch: ["**/__tests__/**/*.test.ts"],
  setupFiles: ["<rootDir>/test/setupEnv.ts"],
  moduleNameMapper: {
    // The real @prisma/client is generated by `prisma generate` (see README).
    // For fast, DB-less unit/integration tests we swap in a lightweight stub
    // that mirrors the enums and error classes our code relies on.
    "^@prisma/client$": "<rootDir>/test/mocks/prismaClientMock.ts",
  },
  transform: {
    "^.+\\.ts$": ["ts-jest", { isolatedModules: true }],
  },
  clearMocks: true,
  collectCoverageFrom: ["src/**/*.ts", "!src/server.ts", "!src/types/**"],
};
